//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchAgencyTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DispatchAgencyTbl()
        {
            this.OrderDispatchTbls = new HashSet<OrderDispatchTbl>();
        }
    
        public long DispatchAgencyID { get; set; }
        public string DispatchAgencyName { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDispatchTbl> OrderDispatchTbls { get; set; }
    }
}
