//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDispatchTbl
    {
        public long OrderDispatchID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<long> AgencyID { get; set; }
        public string DocketNo { get; set; }
    
        public virtual DispatchAgencyTbl DispatchAgencyTbl { get; set; }
        public virtual OrderTbl OrderTbl { get; set; }
    }
}
