//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTbl()
        {
            this.CartTbls = new HashSet<CartTbl>();
            this.OrderDetTbls = new HashSet<OrderDetTbl>();
        }
    
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string ProductDesc { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string MfgName { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartTbl> CartTbls { get; set; }
        public virtual CategoryTbl CategoryTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetTbl> OrderDetTbls { get; set; }
    }
}
